version: '2'

services:
  fish1:
    image: clockworksoul/smudge:latest
    command: "/smudge -node fish2"
    networks:
      - pond

  fish2:
    image: clockworksoul/smudge:latest
    command: "/smudge -node fish1"
    networks:
      - pond

networks:
  pond:
